<div class="col-12 col-xl-6 mb-4">
    <div class="card">
        <div class="card-body text-center">
            <h5 class="h5-responsive $Extras.color-text">$obs.label.outTemp</h5>
            <div id="tempchart"></div>
        </div>
    </div>
</div>
<div class="col-12 col-xl-6 mb-4">
    <div class="card">
        <div class="card-body text-center">
            <h5 class="h5-responsive $Extras.color-text">$obs.label.windchill & $obs.label.heatindex</h5>
            <div id="wchichart"></div>
        </div>
    </div>
</div>

<div class="col-12 col-xl-6 mb-4">
    <div class="card">
        <div class="card-body text-center">
            <h5 class="h5-responsive $Extras.color-text">$obs.label.barometer</h5>
            <div id="barometerchart"></div>
        </div>
    </div>
</div>
<div class="col-12 col-xl-6 mb-4">
    <div class="card">
        <div class="card-body text-center">
            <h5 class="h5-responsive $Extras.color-text">$obs.label.rain</h5>
            <div id="rainchart"></div>
        </div>
    </div>
</div>

<div class="col-12 col-xl-6 mb-4">
    <div class="card">
        <div class="card-body text-center">
            <h5 class="h5-responsive $Extras.color-text">$obs.label.windSpeed</h5>
            <div id="windchart"></div>
        </div>
    </div>
</div>
<div class="col-12 col-xl-6 mb-4">
    <div class="card">
        <div class="card-body text-center">
            <h5 class="h5-responsive $Extras.color-text">$obs.label.windvec</h5>
            <div id="windvectorchart"></div>
        </div>
    </div>
</div>

<div class="col-12 col-xl-6 mb-4">
    <div class="card">
        <div class="card-body text-center">
            <h5 class="h5-responsive $Extras.color-text">$obs.label.outHumidity</h5>
            <div id="humiditychart"></div>
        </div>
    </div>
</div>