<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<meta http-equiv="x-ua-compatible" content="ie=edge">

<!-- Google Fonts -->
<link href="https://fonts.googleapis.com/css2?family=Rubik:wght@300;400;700&display=swap" rel="stylesheet">

<!-- Bootstrap core CSS -->
<link rel="stylesheet" href="css/bootstrap.min.css">
<!-- Material Design Bootstrap -->
<link rel="stylesheet" href="css/mdb.min.css">
<!-- Weather Icons -->
<link rel="stylesheet" href="weather-icons/css/weather-icons.min.css">
<link rel="stylesheet" href="weather-icons/css/weather-icons-wind.min.css">
<!-- Your custom styles (optional) -->
<link rel="stylesheet" href="css/style.css">