#errorCatcher Echo
#encoding UTF-8
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<meta http-equiv="x-ua-compatible" content="ie=edge">

<meta name="description" content="$Extras.description">
<meta name="keywords" content="$Extras.keywords">

## Web App
<meta name="mobile-web-app-capable" content="yes">
<meta name="apple-mobile-web-app-title" content="$Extras.Translations[$Extras.language].weather | $station.location">
<meta name="apple-mobile-web-app-capable" content="yes">
<meta name="apple-mobile-web-app-status-bar-style" content="black">
<meta name="application-name" content="$Extras.Translations[$Extras.language].weather | $station.location">

<link href="img/icon-32.png" rel="icon" type="image/png" sizes="32x32">
<link href="img/icon-48.png" rel="icon" type="image/png" sizes="48x48">

<link href="img/icon-192.png" rel="apple-touch-icon">
<link href="img/icon-76.png" rel="apple-touch-icon" sizes="76x76">
<link href="img/icon-120.png" rel="apple-touch-icon" sizes="120x120">
<link href="img/icon-152.png" rel="apple-touch-icon" sizes="152x152">

<link href="img/icon-192.png" rel="icon" sizes="192x192">
<link href="img/icon-128.png" rel="icon" sizes="128x128">

<link href="manifest.json" rel="manifest">

## Bootstrap core CSS
<link rel="stylesheet" href="css/bootstrap.min.css">

## MDB + skin style
<link rel="stylesheet" href="css/style.min.css">

## Weather Icons
<link rel="stylesheet" href="weather-icons/css/weather-icons.min.css">
<link rel="stylesheet" href="weather-icons/css/weather-icons-wind.min.css">
